### ISSUE TITLE
Unintended conversion

### ISSUE THREAD

**Issue by znicholls** [openscm/openscm-units#12]
**Describe the bug**

At the moment it's possible to convert from NH3 to CO2 when in a context, this shouldn't happen.

**Failing Test**

```python
def test_nh3_doesnt_convert():
    with pytest.raises(DimensionalityError):
        with unit_registry.context("AR5GWP100"):
            (1 * unit_registry("Mt NH3 / yr")).to("Mt CO2 / yr")
```

**Expected behavior**

Raise an error instead.

**Screenshots**

**System (please complete the following information):**

 - OS: [e.g. Windows, Linux, macOS]
 - Python version [e.g. Python 3.5] and output of `conda list --export` and `pip freeze` as applicable

**Additional context**

**Comment by mikapfl** [comment]
This can probably only be solved by treating ammonia / NH3 like NOx and changing the definition from:
```python
"NH3": ["14/17 * N", "ammonia"],
```
to
```python
"NH3": "NH3",
"ammonia": ["NH3"],
```
and maybe adding an `NH3_conversions` context analogous to the `NOx_conversions` one.

Do you think this would be a useful solution? If you want to, I could write a pull request.

**Comment by znicholls** [comment]
> Do you think this would be a useful solution?

Yep perfect! If you have a moment, a PR would be much appreciated
