### ISSUE TITLE
Export ScmUnitRegistry class

### ISSUE THREAD

**Issue by mikapfl** [openscm/openscm-units#13]
At the moment, `src/openscm_units/__init__.py` only imports `unit_registry.unit_registry`, so that the only way to get the `ScmUnitRegistry` class is:
```python
import openscm_units

ScmUnitRegistry = openscm_units.unit_registry.__class__
```
which is quite a mouthful and looks fishy. Is there a reason you hide the ScmUnitRegistry class?

I would propose to add something like
```python
from .unit_registry import ScmUnitRegistry
```
to `__init__.py`, so that `ScmUnitRegistry` can be imported normally. If you don't see a reason why not, I can also provide a pull request.

**Comment by znicholls** [comment]
You can also do `from openscm_units.unit_registry import ScmUnitRegistry`, does that solve the problem?

**Comment by mikapfl** [comment]
Hi,

Thanks, yes, that is possible, true. I thought that wouldn't be possible because openscm_units.unit_registry is the registry itself, not a module, so `import openscm_units; openscm_units.unit_registry.ScmUnitRegistry` doesn't work, but at import time it is possible.

If you don't really want ScmUnitRegistry to be part of the public API then this is fine. If you want it to be part of the public API then it would be great to have available as openscm_units.ScmUnitRegistry directly.

Cheers

Mika

**Comment by znicholls** [comment]
> If you don't really want ScmUnitRegistry to be part of the public API then this is fine

`from openscm_units.unit_registry import ScmUnitRegistry` is part of the public API (there's no underscores anywhere and the only thing which makes something 'private' in Python is beginning with underscores or do I misunderstand)? I'm happy to bring it up a level so you can just do `from openscm_units import ScmUnitRegistry` (just to check, am I missing something or is the benefit that it saves typing an extra `.unit_registry`?).

**Comment by mikapfl** [comment]
The main benefit is that I can use

```python
import openscm_units

[...]
openscm_units.ScmUnitRegistry()
```

while at the moment, this is not possible:
```python
import openscm_units
import openscm_units.unit_registry
[…]
openscm_units.unit_registry.ScmUnitRegistry()
```
because that just gives a `UndefinedUnitError: 'ScmUnitRegistry' is not defined in the unit registry`. So I have to use the `from ... import ...` version of the import statement instead of the somewhat more standard `import ...` version.

**Comment by znicholls** [comment]
ok make a pull request with whatever you'd prefer

**Comment by znicholls** [comment]
having `unit_registry` twice certainly creates more headaches than it should

**Comment by znicholls** [comment]
> ok make a pull request with whatever you'd prefer

To avoid having the module and object having the same name, you could change the hierarchy to `openscm_units._unit_registry.unit_registry` then change `__init__.py` to 

```python
from openscm_units._unit_registry import unit_registry, ScmUnitRegistry
```

It breaks the API but there's so few dependencies it'll be fine (https://github.com/openscm/openscm-units/network/dependents).

**Comment by mikapfl** [comment]
Why isn't the issue auto-closed? Anyway, it's done. :heavy_check_mark:
