### ISSUE TITLE
AR5 CCF GWPs

### ISSUE THREAD

**Issue by JGuetschow** [openscm/openscm-units#22]
**Is your feature request related to a problem? Please describe.**

I need AR5 GWPs with climate-carbon feedbacks for PRIMAP2 (which uses openscm-units)

**Describe the solution you'd like**

I forked openscm-units and will add the AR5CCF GWPs. I will make a pull request once I'm done. Does that work for you?

**Comment by znicholls** [comment]
Sounds good
