### ISSUE TITLE
make github release from tag

### ISSUE THREAD

**Issue by mikapfl** [openscm/openscm-units#26]
**Describe the bug**

The github overview page still shows 0.2.0 as the latest release.

**Expected behavior**

Github should show 0.3.0 as the latest release, like pypi.

**Additional context**

0.3.0 is shown as a tag, not as a release. Making a release from the tag should fix it.

**Comment by znicholls** [comment]
Did a release as a hot fix, couple of questions below.

> The github overview page

What is this?

Do you know of any github actions which automate creating a release? Want to make a PR?

**Comment by mikapfl** [comment]
> Did a release as a hot fix, couple of questions below.
> 
> > The github overview page
> 
> What is this?
> 

I mean the right-hand box saying "releases" at https://github.com/openscm/openscm-units .

> Do you know of any github actions which automate creating a release? Want to make a PR?

So far, I'm doing releases by hand myself. But that should be possible. I'll investigate a bit and will make a PR if I find anything.

**Comment by mikapfl** [comment]
So, after getting distracted by probably more important things than automating this, here is a PR which seems to work. Worked in my fork, anyway (now I have to find out how to get rid of the test releases in my fork...):
https://github.com/openscm/openscm-units/pull/27

**Comment by mikapfl** [comment]
I hope this works now, we'll know after the next release. (-:
